# Generated by Django 4.2.2 on 2023-09-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_is_admin"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
