# Generated by Django 4.2.2 on 2023-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(blank=True, to="core.ingredient"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
    ]
